spring:
  cloud:
    config:
      uri: http://localhost:8888
#    compatibility-verifier:
#      enabled: false
  config:
    import: "configserver:"
  application:
    name:  agent-service-application


#management:
#  tracing:
#    sampling:
#      probability: 0.1

