spring:
  cloud:
    config:
      uri: http://localhost:8888
    circuitbreaker:
      resilience4j:
        enabled: true
  config:
    import: "configserver:"
  application:
    name:  user-profile-service-application
  sleuth:
    enabled: true
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: config-server

management:
  tracing:
    sampling:
      probability: 1

