###### port #####
#server:
#  port: ${SELLER_SERVER_PORT}
#
###### data postgresql #####
#spring:
#  datasource:
#    url: jdbc:${SELLER_DB_PROTOCOL}://${SELLER_DB_IP}:${SELLER_DB_PORT}/${SELLER_DB_NAME}   # PostgreSQL veritabanı URL'si
#    username: ${SELLER_DB_USERNAME}                                    # Veritabanı kullanıcı adı
#    password: ${SELLER_DB_PASSWORD}                                 # Veritabanı şifresi
#    driver-class-name: ${SELLER_DB_DRIVER}            # PostgreSQL JDBC sürücüsü
#  jpa:
#    hibernate:
#      ddl-auto: update                                 # Veritabanı şemasının otomatik güncellenmesi
#    show-sql: true
#
###### swagger-ui path #####
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#
#
###### 1000L * 60 * 5 minutes
#auth-service:
#  secret:
#    key: ${SELLER_SECRET_KEY}
#  issuer: ${SELLER_ISSUER}
#  expire:
#    date: 300000











##### port #####
server:
  port: 9095

##### data postgresql #####
spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: seller-service
  datasource:
    url: jdbc:postgresql://localhost:5432/Micro_SellerServiceDB   # PostgreSQL veritabanı URL'si
    username: postgres                                    # Veritabanı kullanıcı adı
    password: 123456789                                  # Veritabanı şifresi
    driver-class-name: org.postgresql.Driver             # PostgreSQL JDBC sürücüsü
  jpa:
    hibernate:
      ddl-auto: update                                 # Veritabanı şemasının otomatik güncellenmesi
    show-sql: true

##### swagger-ui path #####
springdoc:
  swagger-ui:
    path: /swagger-ui.html


##### 1000L * 60 * 5 minutes
auth-service:
  secret:
    key: Istanbul34
  issuer: Ankara06
  expire:
    date: 300000
