spring:
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: "configserver:"
  application:
    name:  buyer-service-application

management:
  tracing:
    sampling:
      probability: 1