

###### port #####
#server:
#  port: ${PORPERTY_SERVER_PORT}
#
###### data postgresql #####
#spring:
#  datasource:
#    url: jdbc:${PORPERTY_DB_PROTOCOL}://${PORPERTY_DB_IP}:${PORPERTY_DB_PORT}/${PORPERTY_DB_NAME}   # PostgreSQL veritabanı URL'si
#    username: ${PORPERTY_DB_USERNAME}                                    # Veritabanı kullanıcı adı
#    password: ${PORPERTY_DB_PASSWORD}                                 # Veritabanı şifresi
#    driver-class-name: ${PORPERTY_DB_DRIVER}            # PostgreSQL JDBC sürücüsü
#  jpa:
#    hibernate:
#      ddl-auto: update                                 # Veritabanı şemasının otomatik güncellenmesi
#    show-sql: true
#
###### swagger-ui path #####
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#
#
###### 1000L * 60 * 5 minutes
#auth-service:
#  secret:
#    key: ${PORPERTY_SECRET_KEY}
#  issuer: ${PORPERTY_ISSUER}
#  expire:
#    date: 300000











##### port #####
server:
  port: 9094

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: property-service
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0
  datasource:
    url: jdbc:postgresql://localhost:5432/Micro_PropertyServiceDB   # PostgreSQL veritabanı URL'si
    username: postgres                                    # Veritabanı kullanıcı adı
    password: 123456789                                  # Veritabanı şifresi
    driver-class-name: org.postgresql.Driver             # PostgreSQL JDBC sürücüsü
  jpa:
    hibernate:
      ddl-auto: update                                 # Veritabanı şemasının otomatik güncellenmesi
    show-sql: true

##### swagger-ui path #####
springdoc:
  swagger-ui:
    path: /swagger-ui.html


##### 1000L * 60 * 5 minutes
auth-service:
  secret:
    key: Istanbul34
  issuer: Ankara06
  expire:
    date: 300000
