server:
  port: 8888

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: config-server-remote
  cloud:
    config:
      server:
        git:
          uri: ${GITHUB_CONFIG_PATH_PROJECT}
          default-label: main
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_TOKEN_KEY}