# Use root/example as user/password credentials
version: '3.1'

services:

  postgres:
    image: postgres:16.0
    ports:
      - 9999:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  zipkin-server:
    image: openzipkin/zipkin:3.0.6
    container_name: zipkin-server
    expose:
      - '9411'
    ports:
      - '9411:9411'

#  mongo:
#    image: mongo
#    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
#
#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "user"
    ports:
      - "5672:5672" # RabbitMQ sunucu portu
      - "15672:15672" # RabbitMQ Management Plugin Web Arayüzü
    labels:
      NAME: "rabbitmq"
    volumes:
      - "./data:/var/lib/rabbitmq" # Verileri kalıcı hale getirme