@echo off
setx AUTH_SERVER_PORT "KENDI_VERILERINI_YAZ"

setx AUTH_DB_PROTOCOL "KENDI_VERILERINI_YAZ"
setx AUTH_DB_IP "KENDI_VERILERINI_YAZ"
setx AUTH_DB_PORT "KENDI_VERILERINI_YAZ"
setx AUTH_DB_NAME "KENDI_VERILERINI_YAZ"
setx AUTH_DB_DRIVER "KENDI_VERILERINI_YAZ"

setx AUTH_DB_USERNAME "KENDI_VERILERINI_YAZ"
setx AUTH_DB_PASSWORD "KENDI_VERILERINI_YAZ"
setx AUTH_SECRET_KEY "KENDI_VERILERINI_YAZ"
setx AUTH_ISSUER "KENDI_VERILERINI_YAZ"